// generated by yolm csv-analyze
import { addTable, addScriptDbDefinition } from "@yolm/boost/appHelpers";

addScriptDbDefinition("csv", () => {
  addTable("Category", (table) => {
    table.tinyUint("categoryID").notNull();
    table.string("categoryName", 14).notNull();
    table.string("description", 55).notNull();
    table.string("picture", 256).notNull();
  });
  addTable("Shipper", (table) => {
    table.tinyUint("shipperID").notNull();
    table.string("companyName", 16).notNull();
    table.string("phone", 14).notNull();
  });
  addTable("Supplier", (table) => {
    table.tinyUint("supplierID").notNull();
    table.string("companyName", 38).notNull();
    table.string("contactName", 26).notNull();
    table.string("contactTitle", 28).notNull();
    table.string("address", 45).notNull();
    table.string("city", 13).notNull();
    table.string("region", 8);
    table.string("postalCode", 8).notNull();
    table.string("country", 11).notNull();
    table.string("phone", 15).notNull();
    table.string("fax", 15);
    table.string("homePage", 94);
  });
  addTable("Employee", (table) => {
    table.tinyUint("employeeID").notNull();
    table.string("lastName", 9).notNull();
    table.string("firstName", 8).notNull();
    table.string("title", 24).notNull();
    table.string("titleOfCourtesy", 4).notNull();
    table.string("birthDate", 23).notNull();
    table.string("hireDate", 23).notNull();
    table.string("address", 29).notNull();
    table.string("city", 8).notNull();
    table.string("region", 2);
    table.string("postalCode", 7).notNull();
    table.string("country", 3).notNull();
    table.string("homePhone", 14).notNull();
    table.smallUint("extension").notNull();
    table.string("photo", 256).notNull();
    table.string("notes", 253).notNull();
    table.tinyUint("reportsTo");
    table.string("photoPath", 38).notNull();
  });
  addTable("Product", (table) => {
    table.tinyUint("productID").notNull();
    table.string("productName", 33).notNull();
    table.tinyUint("supplierID").notNull();
    table.tinyUint("categoryID").notNull();
    table.string("quantityPerUnit", 20).notNull();
    table
      .decimal("unitPrice", { precision: 5, scale: 2, signed: false })
      .notNull();
    table.tinyUint("unitsInStock").notNull();
    table.tinyUint("unitsOnOrder").notNull();
    table.tinyUint("reorderLevel").notNull();
    table.tinyUint("discontinued").notNull();
  });
  addTable("Customer", (table) => {
    table.string("customerID", 5).notNull();
    table.string("companyName", 36).notNull();
    table.string("contactName", 23).notNull();
    table.string("contactTitle", 30).notNull();
    table.string("address", 47).notNull();
    table.string("city", 17).notNull();
    table.string("region", 13);
    table.string("postalCode", 9);
    table.string("country", 11).notNull();
    table.string("phone", 17).notNull();
    table.string("fax", 17);
  });
  addTable("Order", (table) => {
    table.smallUint("orderID").notNull();
    table.string("customerID", 5).notNull();
    table.tinyUint("employeeID").notNull();
    table.string("orderDate", 23).notNull();
    table.string("requiredDate", 23).notNull();
    table.string("shippedDate", 23);
    table.tinyUint("shipVia").notNull();
    table
      .decimal("freight", { precision: 6, scale: 2, signed: false })
      .notNull();
    table.string("shipName", 34).notNull();
    table.string("shipAddress", 47).notNull();
    table.string("shipCity", 15).notNull();
    table.string("shipRegion", 13);
    table.string("shipPostalCode", 9);
    table.string("shipCountry", 11).notNull();
  });
  addTable("OrderDetails", (table) => {
    table.smallUint("orderID").notNull();
    table.tinyUint("productID").notNull();
    table
      .decimal("unitPrice", { precision: 5, scale: 2, signed: false })
      .notNull();
    table.tinyUint("quantity").notNull();
    table
      .decimal("discount", { precision: 2, scale: 2, signed: false })
      .notNull();
  });
});
