name: Release testing version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Once https://github.com/oven-sh/setup-bun/pull/16 is merged we should use it instead
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "18"

      # Install dependencies
      - run: npm install

      - run: npm run build

      - run: npm run create-ts

      - name: Publish
        run: npm publish --verbose --access public --tag internal-testing
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
